import { GameEntry } from "./types";

/**
 * Static game database.
 *
 * CLUE ORDER: length → platforms → year → genre → developer → coreLoop
 *
 * WRITING GUIDELINES:
 * - length: First-playthrough estimate. Be specific ("6–8 hours") not vague ("medium").
 *   Include qualifiers when relevant ("40–60 hours for main story, 100+ for completion").
 * - coreLoop: One sentence describing what you DO, not what the game IS ABOUT.
 *   Good: "Dash, wall-climb, and air-dash through precision platforming rooms, dying and retrying in seconds."
 *   Bad: "A platformer about climbing a mountain." (that's a description, not a loop)
 *   The loop should be recognizable to someone who's played the game and
 *   unmistakable once combined with the other 5 clues.
*/

// Seeded shuffle so we can re-randomize the ordering once while keeping the
// daily puzzle mapping consistent across reloads.
const SHUFFLE_SEED = 1710002;

function mulberry32(a: number): () => number {
  return () => {
    let t = (a += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function seededShuffle<T>(arr: T[], seed: number): T[] {
  const out = [...arr];
  const rnd = mulberry32(seed);
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    const tmp = out[i];
    out[i] = out[j];
    out[j] = tmp;
  }
  return out;
}

const RAW_GAMES_DB: GameEntry[] = [
  // ============================================================
  // INDIE / EXPERIMENTAL
  // ============================================================
  {
    title: "Outer Wilds",
    developer: "Mobius Digital",
    year: 2019,
    genre: "Exploration / Mystery",
    platforms: "PC, PS4, Xbox, Switch",
    length: "15–20 hours",
    coreLoop: "Explore a solar system within a 22-minute time loop, piecing together an ancient mystery from environmental clues before the sun explodes.",
    color: "#1a3a5c",
  },
  {
    title: "Celeste",
    developer: "Maddy Thorson",
    year: 2018,
    genre: "Platformer",
    platforms: "PC, PS4, Xbox, Switch",
    length: "6–8 hours",
    coreLoop: "Dash, wall-climb, and air-dash through precision platforming rooms, dying and retrying in seconds with instant respawn.",
    color: "#6b2fa0",
  },
  {
    title: "Inside",
    developer: "Playdead",
    year: 2016,
    genre: "Puzzle Platformer",
    platforms: "PC, PS4, Xbox, Switch",
    length: "3–4 hours",
    coreLoop: "Move right through a wordless dystopia, solving physics-based environmental puzzles to avoid capture and death.",
    color: "#2c2c2c",
  },
  {
    title: "Kentucky Route Zero",
    developer: "Cardboard Computer",
    year: 2020,
    genre: "Adventure / Magical Realism",
    platforms: "PC, PS4, Xbox, Switch",
    length: "6–8 hours",
    coreLoop: "Navigate dialogue choices and point-and-click exploration through surreal, stage-like scenes along a secret highway beneath Kentucky.",
    color: "#1e3326",
  },
  {
    title: "Hollow Knight",
    developer: "Team Cherry",
    year: 2017,
    genre: "Metroidvania",
    platforms: "PC, PS4, Xbox, Switch",
    length: "25–40 hours",
    coreLoop: "Explore an interconnected underground kingdom, fighting bugs with a nail, unlocking movement abilities to reach new areas, and resting at benches to save.",
    color: "#1a1a2e",
  },
  {
    title: "Hades",
    developer: "Supergiant Games",
    year: 2020,
    genre: "Roguelike / Action",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "20–30 hours",
    coreLoop: "Fight through randomized rooms of enemies using a weapon and god-given boons, die, return to a hub with permanent upgrades, and advance the story with each run.",
    color: "#a0522d",
  },
  {
    title: "Disco Elysium",
    developer: "ZA/UM",
    year: 2019,
    genre: "RPG / Detective",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "25–35 hours",
    coreLoop: "Investigate a murder through dialogue trees and skill checks, where your own psyche's competing voices shape how you interpret every conversation.",
    color: "#4a6741",
  },
  {
    title: "Return of the Obra Dinn",
    developer: "Lucas Pope",
    year: 2018,
    genre: "Mystery / Logic Puzzle",
    platforms: "PC, PS4, Xbox, Switch",
    length: "8–12 hours",
    coreLoop: "Use a pocket watch to witness the moment of each crew member's death, then cross-reference visual and audio clues to identify who they were and what killed them.",
    color: "#e8e8d0",
  },
  {
    title: "Undertale",
    developer: "Toby Fox",
    year: 2015,
    genre: "RPG",
    platforms: "PC, PS4, Switch",
    length: "5–7 hours",
    coreLoop: "Navigate bullet-hell-style attack patterns in turn-based encounters, choosing to fight or spare every enemy through a mercy system that changes the story.",
    color: "#222034",
  },
  {
    title: "The Witness",
    developer: "Thekla, Inc.",
    year: 2016,
    genre: "Puzzle / Exploration",
    platforms: "PC, PS4, Xbox",
    length: "15–25 hours",
    coreLoop: "Solve increasingly complex line-drawing maze puzzles on panels scattered across an open island, learning each area's unique rule set through observation.",
    color: "#5c8a4d",
  },
  {
    title: "Braid",
    developer: "Jonathan Blow",
    year: 2008,
    genre: "Puzzle Platformer",
    platforms: "PC, PS3, Xbox 360",
    length: "4–6 hours",
    coreLoop: "Manipulate time — rewinding, slowing, and splitting it — to solve platforming puzzles and collect jigsaw pieces across thematic worlds.",
    color: "#c97b3d",
  },
  {
    title: "Limbo",
    developer: "Playdead",
    year: 2010,
    genre: "Puzzle Platformer",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One, Switch",
    length: "3–4 hours",
    coreLoop: "Move through a monochromatic, hostile world solving physics puzzles and avoiding traps, dying gruesomely and restarting from nearby checkpoints.",
    color: "#1a1a1a",
  },
  {
    title: "Stardew Valley",
    developer: "ConcernedApe",
    year: 2016,
    genre: "Simulation / RPG",
    platforms: "PC, PS4, Xbox, Switch, Mobile",
    length: "50–100+ hours",
    coreLoop: "Farm crops, raise animals, mine resources, fish, and build relationships with townsfolk across seasons, reinvesting profits to expand your homestead.",
    color: "#4a8c3f",
  },
  {
    title: "Spelunky 2",
    developer: "Mossmouth",
    year: 2020,
    genre: "Roguelike / Platformer",
    platforms: "PC, PS4, Switch",
    length: "50+ hours for credits",
    coreLoop: "Navigate procedurally generated caves full of traps and enemies in short, high-stakes runs where a single mistake cascades into death and a full restart.",
    color: "#c4a35a",
  },
  {
    title: "Neon White",
    developer: "Angel Matrix",
    year: 2022,
    genre: "FPS / Speedrunning",
    platforms: "PC, PS4, PS5, Switch",
    length: "7–10 hours",
    coreLoop: "Blitz through short levels by shooting demons and discarding weapon cards to gain movement abilities like double jumps and dashes, chasing faster completion times.",
    color: "#e8e8e8",
  },
  {
    title: "Tunic",
    developer: "Andrew Shouldice",
    year: 2022,
    genre: "Action / Adventure",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "12–15 hours",
    coreLoop: "Explore an isometric world as a small fox, fighting enemies with a sword and shield while discovering and decoding pages of an in-game instruction manual written in a foreign script.",
    color: "#3fa67e",
  },
  {
    title: "Papers, Please",
    developer: "Lucas Pope",
    year: 2013,
    genre: "Simulation / Puzzle",
    platforms: "PC, Mobile",
    length: "4–6 hours",
    coreLoop: "Inspect travelers' documents at a border checkpoint against an ever-growing rulebook, stamping passports approved or denied while balancing income against moral choices.",
    color: "#5a5a3c",
  },
  {
    title: "Slay the Spire",
    developer: "MegaCrit",
    year: 2019,
    genre: "Roguelike / Deckbuilder",
    platforms: "PC, PS4, Xbox, Switch, Mobile",
    length: "50+ hours for credits",
    coreLoop: "Draft cards after each combat encounter to build a synergistic deck, manage HP across three acts of increasingly difficult fights, and start over on death with meta-progression.",
    color: "#6a1b3d",
  },
  {
    title: "What Remains of Edith Finch",
    developer: "Giant Sparrow",
    year: 2017,
    genre: "Adventure / Walking Sim",
    platforms: "PC, PS4, Xbox, Switch",
    length: "2–3 hours",
    coreLoop: "Walk through a labyrinthine family house, entering bedrooms to play through short vignettes that each use a unique mechanic to depict a family member's final moments.",
    color: "#4a3728",
  },
  {
    title: "Inscryption",
    developer: "Daniel Mullins",
    year: 2021,
    genre: "Deckbuilder / Horror",
    platforms: "PC, PS4, PS5, Switch",
    length: "10–12 hours",
    coreLoop: "Play cards with blood sacrifices against a shadowy opponent in a cabin, solving escape-room puzzles between rounds, as the game dismantles and rebuilds its own rules across acts.",
    color: "#0d0d0d",
  },
  {
    title: "Katamari Damacy",
    developer: "Namco",
    year: 2004,
    genre: "Puzzle / Action",
    platforms: "PS2, Switch, PC",
    length: "4–6 hours",
    coreLoop: "Roll an adhesive ball across environments, picking up increasingly larger objects to grow from thumbtacks to buildings within a time limit.",
    color: "#7dc95e",
  },
  {
    title: "Spelunky",
    developer: "Mossmouth",
    year: 2012,
    genre: "Roguelike / Platformer",
    platforms: "PC, PS3, PS Vita, Xbox 360",
    length: "50+ hours for credits",
    coreLoop: "Descend through procedurally generated caves using ropes and bombs, learning systemic interactions between traps, enemies, and items through repeated deaths.",
    color: "#b8860b",
  },
  {
    title: "FEZ",
    developer: "Polytron",
    year: 2012,
    genre: "Puzzle Platformer",
    platforms: "PC, PS3, PS4, PS Vita, Xbox 360, Switch",
    length: "5–8 hours",
    coreLoop: "Rotate a 2D world in 3D space to reveal hidden paths and collect cube fragments, with deeper cryptographic puzzles embedded in the environment.",
    color: "#ffe066",
  },
  {
    title: "Hotline Miami",
    developer: "Dennaton Games",
    year: 2012,
    genre: "Top-Down Action",
    platforms: "PC, PS3, PS4, PS Vita, Switch",
    length: "3–5 hours",
    coreLoop: "Storm neon-lit buildings from a top-down view, killing every enemy in a floor with one-hit-kill brutality, dying instantly and restarting until the sequence is flawless.",
    color: "#ff1493",
  },
  {
    title: "Shovel Knight",
    developer: "Yacht Club Games",
    year: 2014,
    genre: "Platformer",
    platforms: "PC, PS3, PS4, Xbox One, Wii U, Switch, 3DS",
    length: "6–8 hours",
    coreLoop: "Bounce on enemies with a downward shovel strike, collect treasure across themed stages, and spend gold on upgrades between levels in a retro 2D platformer.",
    color: "#2980b9",
  },
  {
    title: "Ori and the Blind Forest",
    developer: "Moon Studios",
    year: 2015,
    genre: "Metroidvania / Platformer",
    platforms: "PC, Xbox One, Switch",
    length: "8–10 hours",
    coreLoop: "Navigate a lush forest through acrobatic platforming, unlocking movement abilities to access new areas while fleeing from set-piece escape sequences.",
    color: "#8ac6d1",
  },
  {
    title: "Ori and the Will of the Wisps",
    developer: "Moon Studios",
    year: 2020,
    genre: "Metroidvania / Platformer",
    platforms: "PC, Xbox One, Xbox Series, Switch",
    length: "10–12 hours",
    coreLoop: "Dash, grapple, and burrow through a decaying forest, fighting enemies with spirit weapons and unlocking traversal abilities across interconnected regions.",
    color: "#5b6abf",
  },
  {
    title: "Cuphead",
    developer: "Studio MDHR",
    year: 2017,
    genre: "Run-and-Gun / Boss Rush",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "8–12 hours",
    coreLoop: "Fight hand-drawn cartoon bosses in extended pattern-memorization duels, dodging projectiles while shooting and parrying pink objects to build a super meter.",
    color: "#c0392b",
  },
  {
    title: "Dead Cells",
    developer: "Motion Twin",
    year: 2018,
    genre: "Roguelike / Metroidvania",
    platforms: "PC, PS4, Xbox One, Switch, Mobile",
    length: "20–40 hours",
    coreLoop: "Fight through procedurally arranged biomes with fast melee and ranged combat, collecting cells from enemies to unlock permanent weapon and path options between runs.",
    color: "#1abc9c",
  },
  {
    title: "Hyper Light Drifter",
    developer: "Heart Machine",
    year: 2016,
    genre: "Action RPG",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "6–8 hours",
    coreLoop: "Dash-slash through neon ruins in fast top-down combat, exploring four wordless regions to collect modules that unlock the path to the final area.",
    color: "#e74c8b",
  },
  {
    title: "Transistor",
    developer: "Supergiant Games",
    year: 2014,
    genre: "Action RPG",
    platforms: "PC, PS4, Switch, Mobile",
    length: "5–7 hours",
    coreLoop: "Combine ability functions into a sentient sword and fight in a hybrid of real-time action and a frozen planning mode that lets you queue up a sequence of moves.",
    color: "#e67e22",
  },
  {
    title: "Bastion",
    developer: "Supergiant Games",
    year: 2011,
    genre: "Action RPG",
    platforms: "PC, PS4, Xbox 360, Switch, Mobile",
    length: "6–8 hours",
    coreLoop: "Fight through isometric levels that assemble beneath your feet as a narrator reacts to your every action in real time, upgrading weapons at a central hub.",
    color: "#2ecc71",
  },
  {
    title: "Pyre",
    developer: "Supergiant Games",
    year: 2017,
    genre: "RPG / Sports",
    platforms: "PC, PS4",
    length: "10–12 hours",
    coreLoop: "Lead a band of exiles through a purgatory-like wilderness, competing in 3-on-3 mystical ball games called Rites to earn freedom for one companion at a time.",
    color: "#9b59b6",
  },
  {
    title: "Firewatch",
    developer: "Campo Santo",
    year: 2016,
    genre: "Adventure / Walking Sim",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "3–4 hours",
    coreLoop: "Patrol a Wyoming wilderness as a fire lookout, navigating by compass and map while uncovering a mystery through walkie-talkie conversations with your supervisor.",
    color: "#e67e22",
  },
  {
    title: "Gone Home",
    developer: "Fullbright",
    year: 2013,
    genre: "Adventure / Walking Sim",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "1.5–2 hours",
    coreLoop: "Explore a seemingly empty family house in 1995, picking up objects and reading notes to piece together what happened to your sister while you were abroad.",
    color: "#8e6c4f",
  },
  {
    title: "The Stanley Parable",
    developer: "Galactic Cafe",
    year: 2013,
    genre: "Walking Sim / Comedy",
    platforms: "PC",
    length: "1–3 hours",
    coreLoop: "Walk through an office building while a narrator describes your actions, choosing to obey or defy his instructions to discover dozens of divergent endings.",
    color: "#f1c40f",
  },
  {
    title: "The Stanley Parable: Ultra Deluxe",
    developer: "Crows Crows Crows",
    year: 2022,
    genre: "Walking Sim / Comedy",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "3–5 hours",
    coreLoop: "Explore a greatly expanded office where following or defying a narrator leads to new endings, many of which comment on the original game's own legacy and sequel expectations.",
    color: "#f39c12",
  },
  {
    title: "Outer Wilds: Echoes of the Eye",
    developer: "Mobius Digital",
    year: 2021,
    genre: "Exploration / Horror",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "6–10 hours",
    coreLoop: "Discover a hidden location within a familiar solar system, exploring an alien habitat inside a time loop while navigating darkness and stealth-based encounters.",
    color: "#2c1810",
  },
  {
    title: "Cocoon",
    developer: "Geometric Interactive",
    year: 2023,
    genre: "Puzzle / Adventure",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "4–6 hours",
    coreLoop: "Carry orbs that contain entire worlds on your back, hopping between nested realities to solve puzzles that span multiple layers of existence.",
    color: "#c9770a",
  },
  {
    title: "Baba Is You",
    developer: "Hempuli",
    year: 2019,
    genre: "Puzzle",
    platforms: "PC, Switch, Mobile",
    length: "15–30 hours",
    coreLoop: "Push word blocks around a grid to rewrite the rules of each level — 'ROCK IS PUSH' becomes 'ROCK IS YOU' — transforming yourself and the win condition.",
    color: "#2d2d2d",
  },
  {
    title: "Into the Breach",
    developer: "Subset Games",
    year: 2018,
    genre: "Tactics / Roguelike",
    platforms: "PC, Switch, Mobile",
    length: "15–20 hours for credits",
    coreLoop: "Deploy three mechs on a small grid to protect buildings from giant bugs, with perfect information about enemy moves letting you solve each turn like a puzzle.",
    color: "#3498db",
  },
  {
    title: "FTL: Faster Than Light",
    developer: "Subset Games",
    year: 2012,
    genre: "Roguelike / Strategy",
    platforms: "PC, Mobile",
    length: "20+ hours for credits",
    coreLoop: "Manage a spaceship's crew, power, and weapons in real-time pausable combat while jumping between star systems, making risk-reward decisions at each node on a sector map.",
    color: "#34495e",
  },
  {
    title: "Superhot",
    developer: "Superhot Team",
    year: 2016,
    genre: "FPS / Puzzle",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "2–3 hours",
    coreLoop: "Fight red crystalline enemies in a world where time only moves when you move, turning each encounter into a slow-motion tactical puzzle of positioning and timing.",
    color: "#e74c3c",
  },
  {
    title: "Observation",
    developer: "No Code",
    year: 2019,
    genre: "Adventure / Sci-Fi",
    platforms: "PC, PS4",
    length: "4–6 hours",
    coreLoop: "Control a space station's AI systems by switching between cameras and operating station modules to assist an astronaut investigating what went wrong.",
    color: "#1a1a3a",
  },
  {
    title: "Pentiment",
    developer: "Obsidian Entertainment",
    year: 2022,
    genre: "Adventure / Mystery",
    platforms: "PC, Xbox One, Xbox Series, Switch",
    length: "15–20 hours",
    coreLoop: "Investigate murders in a 16th-century Bavarian town through conversations and accusations, with your choices permanently shaping the community across 25 years.",
    color: "#8b4513",
  },
  {
    title: "Vampire Survivors",
    developer: "poncle",
    year: 2022,
    genre: "Action / Roguelike",
    platforms: "PC, Xbox, Switch, Mobile",
    length: "15–30 hours",
    coreLoop: "Move through hordes of monsters while your weapons fire automatically, leveling up every few seconds to choose new weapon synergies and survive for 30 minutes.",
    color: "#4a0e4e",
  },
  {
    title: "Unpacking",
    developer: "Witch Beam",
    year: 2021,
    genre: "Puzzle / Narrative",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "2–3 hours",
    coreLoop: "Unpack boxes into rooms across different stages of a person's life, placing each item where it belongs and piecing together a life story from possessions alone.",
    color: "#d4a5a5",
  },
  {
    title: "Oxenfree",
    developer: "Night School Studio",
    year: 2016,
    genre: "Adventure / Horror",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "4–5 hours",
    coreLoop: "Walk through a haunted island choosing dialogue in real-time conversational branching while tuning a radio to interact with supernatural frequencies.",
    color: "#1a3a5c",
  },
  {
    title: "Sayonara Wild Hearts",
    developer: "Simogo",
    year: 2019,
    genre: "Rhythm / Action",
    platforms: "PC, PS4, Switch, Mobile",
    length: "1–1.5 hours",
    coreLoop: "Race, fly, and dance through a pop-music fever dream, collecting hearts in rhythm-synced stages that shift genres from motorcycle chasing to sword fighting.",
    color: "#ff6b9d",
  },
  {
    title: "Norco",
    developer: "Geography of Robots",
    year: 2022,
    genre: "Point-and-Click / Sci-Fi",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "4–6 hours",
    coreLoop: "Point-and-click through a surreal, industrial Southern Gothic Louisiana, interrogating characters and solving puzzles to find your missing brother.",
    color: "#4a6741",
  },
  {
    title: "Signalis",
    developer: "rose-engine",
    year: 2022,
    genre: "Survival Horror",
    platforms: "PC, PS4, Xbox, Switch",
    length: "8–12 hours",
    coreLoop: "Explore claustrophobic facilities as a Replika technician, managing limited inventory and ammo in classic fixed-camera survival horror while unraveling a fragmented love story.",
    color: "#8b0000",
  },
  {
    title: "Lorelei and the Laser Eyes",
    developer: "Simogo",
    year: 2024,
    genre: "Puzzle / Mystery",
    platforms: "PC, PS5, Switch",
    length: "10–15 hours",
    coreLoop: "Wander a strange hotel solving hundreds of interconnected puzzles — codes, riddles, mazes, logic problems — while unraveling a nonlinear mystery across timelines.",
    color: "#1a1a1a",
  },
  {
    title: "Animal Well",
    developer: "Shared Memory",
    year: 2024,
    genre: "Metroidvania / Puzzle",
    platforms: "PC, PS5, Switch",
    length: "6–10 hours, 40+ for full completion",
    coreLoop: "Navigate a dense pixel-art labyrinth using unconventional tools like bubbles, a yo-yo, and a disc, with deeply hidden secrets layered far beyond the first ending.",
    color: "#2d5016",
  },
  {
    title: "Balatro",
    developer: "LocalThunk",
    year: 2024,
    genre: "Roguelike / Deckbuilder",
    platforms: "PC, PS4, PS5, Xbox, Switch, Mobile",
    length: "50+ hours for credits",
    coreLoop: "Play poker hands to score points against escalating chip requirements, buying joker cards that multiply and warp scoring rules into absurd chain reactions.",
    color: "#1a0a2e",
  },
  {
    title: "Celeste 64",
    developer: "Maddy Thorson",
    year: 2024,
    genre: "3D Platformer",
    platforms: "PC",
    length: "15–30 minutes",
    coreLoop: "Dash and climb through a tiny open 3D mountain, collecting strawberries in a compact tribute that translates 2D precision into low-poly 3D space.",
    color: "#9b59b6",
  },
  {
    title: "Subnautica",
    developer: "Unknown Worlds",
    year: 2018,
    genre: "Survival / Exploration",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "30–50 hours",
    coreLoop: "Dive deeper into an alien ocean, gathering resources to build bases and craft vehicles while cataloging creatures and uncovering signals from your crashed ship.",
    color: "#006994",
  },
  {
    title: "Terraria",
    developer: "Re-Logic",
    year: 2011,
    genre: "Sandbox / Action",
    platforms: "PC, PS4, Xbox, Switch, Mobile",
    length: "50–200+ hours",
    coreLoop: "Dig, build, and fight across a procedurally generated 2D world, defeating bosses to unlock new biomes and crafting tiers in a progression loop from wood to endgame.",
    color: "#3c8d2f",
  },
  {
    title: "Minecraft",
    developer: "Mojang",
    year: 2011,
    genre: "Sandbox / Survival",
    platforms: "PC, PS4, Xbox, Switch, Mobile",
    length: "30+ hours for credits",
    coreLoop: "Mine blocks, craft tools, and build structures in a procedural voxel world, surviving nights against monsters and optionally pursuing a boss in another dimension.",
    color: "#5d8c3e",
  },
  {
    title: "Factorio",
    developer: "Wube Software",
    year: 2020,
    genre: "Automation / Strategy",
    platforms: "PC, Switch",
    length: "50–200+ hours",
    coreLoop: "Build and optimize automated factory chains that mine, smelt, assemble, and transport resources across conveyor belts, defending against alien attacks to launch a rocket.",
    color: "#d35400",
  },
  {
    title: "Satisfactory",
    developer: "Coffee Stain Studios",
    year: 2024,
    genre: "Automation / Exploration",
    platforms: "PC",
    length: "80–200+ hours",
    coreLoop: "Build sprawling 3D factories across an alien planet, routing conveyor belts and pipelines between machines to automate increasingly complex production chains.",
    color: "#e67e22",
  },
  {
    title: "Noita",
    developer: "Nolla Games",
    year: 2020,
    genre: "Roguelike / Action",
    platforms: "PC",
    length: "30+ hours for credits",
    coreLoop: "Descend through a pixel-simulated world where every particle is physically modeled, crafting custom wands by combining spell modifiers to create chaotic chain reactions.",
    color: "#6c3483",
  },
  {
    title: "Rain World",
    developer: "Videocult",
    year: 2017,
    genre: "Platformer / Survival",
    platforms: "PC, PS4, Switch",
    length: "15–25 hours",
    coreLoop: "Survive as a small slugcat in a hostile ecosystem of predators and prey, eating enough food to hibernate before lethal rain floods every region on a timer.",
    color: "#5d6d7e",
  },
  {
    title: "Ultrakill",
    developer: "Arsi 'Hakita' Patala",
    year: 2022,
    genre: "FPS",
    platforms: "PC",
    length: "6–10 hours",
    coreLoop: "Chain together stylish FPS combat by parrying projectiles, coin-flipping shots, and healing through blood splatter from enemies killed at close range.",
    color: "#e74c3c",
  },
  {
    title: "Dredge",
    developer: "Black Salt Games",
    year: 2023,
    genre: "Fishing / Horror",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "10–15 hours",
    coreLoop: "Fish during the day using a Tetris-like inventory, sell catches and upgrade your trawler, but avoid staying out past dark when the ocean becomes hostile and aberrant.",
    color: "#1a2a3a",
  },
  {
    title: "The Binding of Isaac: Rebirth",
    developer: "Edmund McMillen / Nicalis",
    year: 2014,
    genre: "Roguelike / Twin-Stick Shooter",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "100+ hours for credits",
    coreLoop: "Shoot tears at enemies through procedurally generated basement rooms, stacking dozens of items that visually and mechanically transform your character each run.",
    color: "#6c3028",
  },
  {
    title: "Darkest Dungeon",
    developer: "Red Hook Studios",
    year: 2016,
    genre: "Roguelike / RPG",
    platforms: "PC, PS4, PS Vita, Xbox, Switch, Mobile",
    length: "40–80 hours",
    coreLoop: "Send expendable heroes into procedural dungeons in turn-based combat, managing their stress and afflictions as much as their health, permanently losing them to madness or death.",
    color: "#2c1810",
  },
  {
    title: "Ape Out",
    developer: "Gabe Cuzzillo",
    year: 2019,
    genre: "Action",
    platforms: "PC, Switch",
    length: "1.5–3 hours",
    coreLoop: "Smash through top-down levels as a gorilla, grabbing and throwing guards while a reactive jazz drum soundtrack punctuates every kill.",
    color: "#e67e22",
  },
  {
    title: "Chicory: A Colorful Tale",
    developer: "Greg Lobanov",
    year: 2021,
    genre: "Adventure / Puzzle",
    platforms: "PC, PS4, PS5, Switch",
    length: "8–12 hours",
    coreLoop: "Paint a black-and-white world back to life using a magic brush, solving puzzles and helping townsfolk while grappling with creative self-doubt.",
    color: "#e8c547",
  },
  {
    title: "Manifold Garden",
    developer: "William Chyr Studio",
    year: 2019,
    genre: "Puzzle",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "5–8 hours",
    coreLoop: "Shift gravity to walk on any surface in impossible Escher-like architecture, carrying color-coded blocks to their matching receptacles across infinite recursive spaces.",
    color: "#5b2c6f",
  },
  {
    title: "Psychonauts 2",
    developer: "Double Fine",
    year: 2021,
    genre: "3D Platformer",
    platforms: "PC, PS4, Xbox One, Xbox Series",
    length: "12–16 hours",
    coreLoop: "Enter people's minds as a psychic agent, platforming through surreal mental landscapes themed around each character's emotional struggles while collecting figments and upgrades.",
    color: "#9b59b6",
  },
  // ============================================================
  // AAA / MAINSTREAM
  // ============================================================
  {
    title: "Sekiro: Shadows Die Twice",
    developer: "FromSoftware",
    year: 2019,
    genre: "Action / Souls-like",
    platforms: "PC, PS4, Xbox",
    length: "30–40 hours",
    coreLoop: "Deflect enemy attacks with precise sword parries to break their posture, then deliver a killing deathblow, using a prosthetic arm for tactical tools.",
    color: "#8b1a1a",
  },
  {
    title: "Dark Souls",
    developer: "FromSoftware",
    year: 2011,
    genre: "Action RPG / Souls-like",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One, Switch",
    length: "40–60 hours",
    coreLoop: "Fight through punishing enemies and bosses using stamina-based melee combat, recover souls from your corpse on death, and unlock shortcuts between bonfires.",
    color: "#3d2b1f",
  },
  {
    title: "Portal 2",
    developer: "Valve",
    year: 2011,
    genre: "Puzzle / FPS",
    platforms: "PC, PS3, Xbox 360",
    length: "7–9 hours",
    coreLoop: "Shoot linked entry and exit portals onto surfaces to redirect yourself, objects, and physics to traverse test chambers and escape a facility run by a murderous AI.",
    color: "#1e6091",
  },
  {
    title: "Shadow of the Colossus",
    developer: "Team Ico",
    year: 2005,
    genre: "Action / Adventure",
    platforms: "PS2, PS3, PS4",
    length: "6–8 hours",
    coreLoop: "Ride across an empty forbidden land to find towering colossi, then climb their bodies to locate and strike glowing weak points.",
    color: "#8a9a5b",
  },
  {
    title: "Elden Ring",
    developer: "FromSoftware",
    year: 2022,
    genre: "Action RPG / Open World",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "60–100+ hours",
    coreLoop: "Explore a vast open world on horseback, discover dungeons and bosses organically, level up at sites of grace, and fight through punishing combat with build-crafted weapons and spells.",
    color: "#6b5b3e",
  },
  {
    title: "Bloodborne",
    developer: "FromSoftware",
    year: 2015,
    genre: "Action RPG / Souls-like",
    platforms: "PS4",
    length: "30–40 hours",
    coreLoop: "Hunt beasts through gothic streets using fast, aggressive trick-weapon combat with a rally system that rewards attacking immediately after taking damage.",
    color: "#2b0a0a",
  },
  {
    title: "Journey",
    developer: "thatgamecompany",
    year: 2012,
    genre: "Adventure",
    platforms: "PS3, PS4, PC",
    length: "1.5–2 hours",
    coreLoop: "Walk and fly through vast desert landscapes toward a distant mountain, occasionally encountering one anonymous companion with no communication except musical chimes.",
    color: "#d4a44c",
  },
  {
    title: "The Last of Us",
    developer: "Naughty Dog",
    year: 2013,
    genre: "Action / Adventure",
    platforms: "PS3, PS4, PS5, PC",
    length: "15–18 hours",
    coreLoop: "Scavenge scarce supplies, craft improvised weapons, and alternate between stealth and desperate combat against infected and hostile humans across a post-apocalyptic road story.",
    color: "#2d4a2e",
  },
  {
    title: "The Last of Us Part II",
    developer: "Naughty Dog",
    year: 2020,
    genre: "Action / Adventure",
    platforms: "PS4, PS5, PC",
    length: "25–30 hours",
    coreLoop: "Alternate between two protagonists hunting each other across a ruined Seattle, using stealth, crafting, and brutal melee combat against human factions and infected.",
    color: "#1a3320",
  },
  {
    title: "Breath of the Wild",
    developer: "Nintendo",
    year: 2017,
    genre: "Action / Adventure / Open World",
    platforms: "Switch, Wii U",
    length: "40–60 hours",
    coreLoop: "Climb, glide, and explore a fully open world, solving physics-based shrine puzzles, cooking food for buffs, and fighting enemies with breakable weapons in any order you choose.",
    color: "#5b9bd5",
  },
  {
    title: "Tears of the Kingdom",
    developer: "Nintendo",
    year: 2023,
    genre: "Action / Adventure / Open World",
    platforms: "Switch",
    length: "50–80 hours",
    coreLoop: "Fuse objects together, build vehicles from parts, rewind time on objects, and ascend through ceilings to solve puzzles and explore a world now extended into the sky and depths.",
    color: "#2c6e49",
  },
  {
    title: "Red Dead Redemption 2",
    developer: "Rockstar Games",
    year: 2018,
    genre: "Action / Adventure / Open World",
    platforms: "PC, PS4, Xbox One",
    length: "50–70 hours",
    coreLoop: "Ride, hunt, and survive across a detailed frontier as an outlaw, managing camp morale and honor while carrying out heists and watching a gang fall apart.",
    color: "#8b4513",
  },
  {
    title: "God of War (2018)",
    developer: "Santa Monica Studio",
    year: 2018,
    genre: "Action / Adventure",
    platforms: "PS4, PC",
    length: "20–25 hours",
    coreLoop: "Throw and recall a magical axe in close-range combat alongside your son, exploring Norse realms connected by a central hub and upgrading gear between story beats.",
    color: "#4a6fa5",
  },
  {
    title: "God of War Ragnarök",
    developer: "Santa Monica Studio",
    year: 2022,
    genre: "Action / Adventure",
    platforms: "PS4, PS5, PC",
    length: "25–35 hours",
    coreLoop: "Wield two elemental weapons — axe and blades — with a companion in tow, solving environmental puzzles and fighting through all nine Norse realms toward Ragnarök.",
    color: "#1c3a5f",
  },
  {
    title: "Half-Life 2",
    developer: "Valve",
    year: 2004,
    genre: "FPS",
    platforms: "PC, Xbox 360, PS3",
    length: "12–15 hours",
    coreLoop: "Fight through a dystopian city and its surroundings using weapons and a gravity gun that turns any physics object into a projectile, with seamless storytelling woven into gameplay.",
    color: "#d35400",
  },
  {
    title: "Portal",
    developer: "Valve",
    year: 2007,
    genre: "Puzzle / FPS",
    platforms: "PC, PS3, Xbox 360",
    length: "2–3 hours",
    coreLoop: "Place entry and exit portals on surfaces to redirect momentum and solve increasingly devious test chambers while a darkly funny AI comments on your progress.",
    color: "#1e90ff",
  },
  {
    title: "BioShock",
    developer: "Irrational Games",
    year: 2007,
    genre: "FPS / Immersive Sim",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One, Switch",
    length: "12–15 hours",
    coreLoop: "Explore a crumbling underwater city using guns and genetic superpowers in tandem, hacking machines, scavenging supplies, and choosing whether to harvest or save Little Sisters.",
    color: "#1a5276",
  },
  {
    title: "Mass Effect 2",
    developer: "BioWare",
    year: 2010,
    genre: "RPG / Third-Person Shooter",
    platforms: "PC, PS3, Xbox 360",
    length: "25–35 hours",
    coreLoop: "Recruit a team of specialists across the galaxy, earn their loyalty through personal missions, and command squad-based cover shooting with pause-and-play power combos.",
    color: "#c0392b",
  },
  {
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    year: 2015,
    genre: "Action RPG / Open World",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "50–100+ hours",
    coreLoop: "Track monsters using detective-like witcher senses, prepare oils and potions before contracts, and make branching narrative choices while exploring a war-torn open world.",
    color: "#1e3a2b",
  },
  {
    title: "Resident Evil 4 (2023)",
    developer: "Capcom",
    year: 2023,
    genre: "Survival Horror / Action",
    platforms: "PC, PS4, PS5, Xbox Series",
    length: "15–20 hours",
    coreLoop: "Fight through swarms of infected villagers with over-the-shoulder shooting and melee finishers, managing an attaché case inventory and buying upgrades from a mysterious merchant.",
    color: "#4a1a0a",
  },
  {
    title: "Resident Evil 2 (2019)",
    developer: "Capcom",
    year: 2019,
    genre: "Survival Horror",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "8–10 hours per campaign",
    coreLoop: "Navigate a zombie-infested police station with limited ammo, solving lock-and-key puzzles while an invincible trenchcoated pursuer stalks you through the halls.",
    color: "#2c1a0e",
  },
  {
    title: "Metal Gear Solid",
    developer: "Konami",
    year: 1998,
    genre: "Stealth / Action",
    platforms: "PS1, PC",
    length: "10–12 hours",
    coreLoop: "Sneak through a military facility using radar, distractions, and cardboard boxes to avoid detection, fighting cinematic boss battles and unraveling a nuclear conspiracy via codec calls.",
    color: "#2e4057",
  },
  {
    title: "Metal Gear Solid V: The Phantom Pain",
    developer: "Konami",
    year: 2015,
    genre: "Stealth / Action / Open World",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One",
    length: "40–60 hours",
    coreLoop: "Infiltrate open-world military outposts using customizable loadouts, a buddy system, and Fulton balloon extraction to kidnap soldiers and expand your private army's base.",
    color: "#5d6d7e",
  },
  {
    title: "Halo: Combat Evolved",
    developer: "Bungie",
    year: 2001,
    genre: "FPS",
    platforms: "Xbox, PC",
    length: "8–10 hours",
    coreLoop: "Fight through alien and undead forces using a two-weapon limit and regenerating shields, driving vehicles across large outdoor arenas on a mysterious ringworld.",
    color: "#2ecc71",
  },
  {
    title: "Doom Eternal",
    developer: "id Software",
    year: 2020,
    genre: "FPS",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "15–20 hours",
    coreLoop: "Kill demons at breakneck speed, chainsawing for ammo, glory-killing for health, and flame-belching for armor to maintain a constant aggressive resource loop.",
    color: "#c0392b",
  },
  {
    title: "Doom (2016)",
    developer: "id Software",
    year: 2016,
    genre: "FPS",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "10–13 hours",
    coreLoop: "Rip and tear through arenas of demons using an arsenal of heavy weapons and glory kills that reward aggression over cover with health drops from staggered enemies.",
    color: "#922b21",
  },
  {
    title: "Control",
    developer: "Remedy Entertainment",
    year: 2019,
    genre: "Action / Adventure",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "10–15 hours",
    coreLoop: "Wield a shape-shifting gun and telekinetic powers through a brutalist government building that shifts its architecture, fighting corrupted agents across surreal office spaces.",
    color: "#922b21",
  },
  {
    title: "Horizon Zero Dawn",
    developer: "Guerrilla Games",
    year: 2017,
    genre: "Action RPG / Open World",
    platforms: "PS4, PC",
    length: "25–40 hours",
    coreLoop: "Hunt robotic dinosaurs with a bow, shooting off armor components to exploit weak points, while uncovering why the old world fell through holographic data logs.",
    color: "#e67e22",
  },
  {
    title: "Death Stranding",
    developer: "Kojima Productions",
    year: 2019,
    genre: "Action / Walking Sim",
    platforms: "PC, PS4, PS5",
    length: "40–60 hours",
    coreLoop: "Haul cargo across a post-apocalyptic America on foot, managing balance and terrain while building infrastructure like bridges and ziplines that persist for other players.",
    color: "#2c3e50",
  },
  {
    title: "Ghost of Tsushima",
    developer: "Sucker Punch",
    year: 2020,
    genre: "Action / Open World",
    platforms: "PS4, PS5, PC",
    length: "25–35 hours",
    coreLoop: "Duel Mongol invaders using stance-switching katana combat, track objectives by following the wind, and choose between honorable samurai tactics and dishonorable ghost techniques.",
    color: "#c0392b",
  },
  {
    title: "Uncharted 4: A Thief's End",
    developer: "Naughty Dog",
    year: 2016,
    genre: "Action / Adventure",
    platforms: "PS4, PS5, PC",
    length: "15–18 hours",
    coreLoop: "Climb, swing, and gun your way through cinematic set pieces, solving environmental traversal puzzles between third-person shootouts in a globe-trotting treasure hunt.",
    color: "#d4a017",
  },
  {
    title: "Dark Souls III",
    developer: "FromSoftware",
    year: 2016,
    genre: "Action RPG / Souls-like",
    platforms: "PC, PS4, Xbox One",
    length: "30–45 hours",
    coreLoop: "Fight through decaying kingdoms using stamina-based combat with faster, more aggressive enemy patterns than its predecessors, linking bonfires and recovering souls from your corpse.",
    color: "#1c2833",
  },
  {
    title: "Demon's Souls (2020)",
    developer: "Bluepoint Games",
    year: 2020,
    genre: "Action RPG / Souls-like",
    platforms: "PS5",
    length: "20–30 hours",
    coreLoop: "Fight through five distinct archstone worlds in methodical souls combat, returning to a central hub between deaths where world tendency shifts based on your actions.",
    color: "#4a4a6a",
  },
  {
    title: "Super Mario Odyssey",
    developer: "Nintendo",
    year: 2017,
    genre: "3D Platformer",
    platforms: "Switch",
    length: "10–15 hours, 40+ for completion",
    coreLoop: "Throw a sentient hat to possess enemies and objects, inheriting their abilities to solve platforming challenges and collect moons across themed sandbox kingdoms.",
    color: "#e74c3c",
  },
  {
    title: "Super Mario Galaxy",
    developer: "Nintendo",
    year: 2007,
    genre: "3D Platformer",
    platforms: "Wii, Switch",
    length: "10–15 hours",
    coreLoop: "Jump across planetoids with spherical gravity, spinning to attack and collecting star bits while navigating inventive galaxy-themed obstacle courses for power stars.",
    color: "#2980b9",
  },
  {
    title: "Super Metroid",
    developer: "Nintendo",
    year: 1994,
    genre: "Metroidvania",
    platforms: "SNES, Switch (NSO)",
    length: "6–8 hours",
    coreLoop: "Explore a hostile alien planet in a nonlinear labyrinth, acquiring beam upgrades and movement abilities to reach deeper areas while fighting biomechanical bosses.",
    color: "#1a1a4e",
  },
  {
    title: "Metroid Dread",
    developer: "MercurySteam / Nintendo",
    year: 2021,
    genre: "Metroidvania",
    platforms: "Switch",
    length: "8–12 hours",
    coreLoop: "Run, slide, and counter-melee through interconnected zones on an alien planet, evading invincible EMMI robots in stealth zones while unlocking abilities to access new areas.",
    color: "#2c3e50",
  },
  {
    title: "Chrono Trigger",
    developer: "Square",
    year: 1995,
    genre: "RPG",
    platforms: "SNES, PS1, DS, PC, Mobile",
    length: "20–25 hours",
    coreLoop: "Travel between eras of history in a turn-based RPG, combining dual and triple tech attacks between party members and making choices that branch toward over a dozen endings.",
    color: "#8e44ad",
  },
  {
    title: "Final Fantasy VII",
    developer: "Square",
    year: 1997,
    genre: "RPG",
    platforms: "PS1, PC, Switch, PS4, Xbox",
    length: "35–50 hours",
    coreLoop: "Fight in ATB turn-based battles using equipped materia that grants spells and abilities, exploring a world of reactors and ruins to stop a megacorporation and a fallen hero.",
    color: "#27ae60",
  },
  {
    title: "Final Fantasy VII Rebirth",
    developer: "Square Enix",
    year: 2024,
    genre: "Action RPG",
    platforms: "PS5, PC",
    length: "50–80 hours",
    coreLoop: "Explore open-world regions and fight in real-time action combat with ATB ability spending, switching between party members and synergizing their unique fighting styles.",
    color: "#1a5276",
  },
  {
    title: "Persona 5 Royal",
    developer: "Atlus",
    year: 2020,
    genre: "RPG / Social Sim",
    platforms: "PS4, PS5, PC, Xbox, Switch",
    length: "80–120 hours",
    coreLoop: "Infiltrate stylized cognitive palaces in turn-based combat by day, then build social bonds and manage time in a Tokyo high school life sim that powers up your personas.",
    color: "#e74c3c",
  },
  {
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    year: 2023,
    genre: "RPG / Tactical",
    platforms: "PC, PS5, Xbox Series",
    length: "80–150 hours",
    coreLoop: "Explore a vast fantasy world in a party-based RPG using D&D 5th edition rules, with dice-roll dialogue checks, turn-based tactical combat, and hundreds of branching story paths.",
    color: "#6c3483",
  },
  {
    title: "Divinity: Original Sin 2",
    developer: "Larian Studios",
    year: 2017,
    genre: "RPG / Tactical",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "60–100 hours",
    coreLoop: "Fight in turn-based tactical combat that combines elemental surfaces — oil, fire, poison, water — with environmental destruction, exploring a deep narrative with full co-op support.",
    color: "#b7950b",
  },
  {
    title: "Halo 3",
    developer: "Bungie",
    year: 2007,
    genre: "FPS",
    platforms: "Xbox 360, PC",
    length: "8–10 hours",
    coreLoop: "Fight through alien and parasite forces with the two-weapon sandbox, grenades, and melee, using deployable equipment and vehicles across large-scale battlefields to finish the fight.",
    color: "#27ae60",
  },
  {
    title: "The Elder Scrolls V: Skyrim",
    developer: "Bethesda Game Studios",
    year: 2011,
    genre: "Action RPG / Open World",
    platforms: "PC, PS3, PS4, PS5, Xbox 360, Xbox One, Xbox Series, Switch",
    length: "50–200+ hours",
    coreLoop: "Roam a vast Nordic open world in first or third person, fighting with weapons, magic, and dragon shouts while joining guilds, clearing dungeons, and absorbing dragon souls.",
    color: "#5d6d7e",
  },
  {
    title: "Fallout: New Vegas",
    developer: "Obsidian Entertainment",
    year: 2010,
    genre: "Action RPG / Open World",
    platforms: "PC, PS3, Xbox 360",
    length: "30–60 hours",
    coreLoop: "Explore a post-nuclear Mojave Desert using real-time or VATS targeting combat, navigating faction politics and speech-check dialogues that dramatically reshape the story.",
    color: "#d4a017",
  },
  {
    title: "Ico",
    developer: "Team Ico",
    year: 2001,
    genre: "Action / Puzzle",
    platforms: "PS2, PS3",
    length: "5–7 hours",
    coreLoop: "Lead a ghostly girl by the hand through a crumbling castle, solving environmental puzzles and fending off shadow creatures with a stick to find an escape together.",
    color: "#b0c4de",
  },
  {
    title: "Silent Hill 2",
    developer: "Konami",
    year: 2001,
    genre: "Survival Horror",
    platforms: "PS2, Xbox, PC",
    length: "8–10 hours",
    coreLoop: "Wander a fog-drenched town fighting disturbing monsters with clumsy combat and limited supplies, solving puzzles in decaying buildings while piecing together why you received a letter from your dead wife.",
    color: "#5d6d7e",
  },
  {
    title: "Silent Hill 2 (2024)",
    developer: "Bloober Team",
    year: 2024,
    genre: "Survival Horror",
    platforms: "PS5, PC",
    length: "12–16 hours",
    coreLoop: "Explore a fog-covered lakeside town in over-the-shoulder survival horror, fighting symbolic monsters with melee and ranged combat while solving environmental puzzles tied to guilt and grief.",
    color: "#4a4a4a",
  },
  {
    title: "Resident Evil Village",
    developer: "Capcom",
    year: 2021,
    genre: "Survival Horror / Action",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "8–10 hours",
    coreLoop: "Fight through a gothic European village of werewolves and vampires using first-person shooting, managing a merchant-based upgrade economy and solving each lord's domain as a distinct horror vignette.",
    color: "#3a1a0a",
  },
  {
    title: "Alan Wake 2",
    developer: "Remedy Entertainment",
    year: 2023,
    genre: "Survival Horror",
    platforms: "PC, PS5, Xbox Series",
    length: "15–20 hours",
    coreLoop: "Alternate between an FBI agent investigating murders and a writer trapped in a dark dimension, using light to weaken enemies and rewriting story elements to reshape reality.",
    color: "#1a1a2e",
  },
  {
    title: "Hitman: World of Assassination",
    developer: "IO Interactive",
    year: 2016,
    genre: "Stealth / Sandbox",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "20–50+ hours",
    coreLoop: "Infiltrate elaborate sandbox levels disguised as anyone, studying target routines to engineer creative assassination opportunities that look like accidents.",
    color: "#c0392b",
  },
  {
    title: "Prey (2017)",
    developer: "Arkane Studios",
    year: 2017,
    genre: "Immersive Sim / FPS",
    platforms: "PC, PS4, Xbox One",
    length: "15–25 hours",
    coreLoop: "Survive aboard a space station overrun by shape-shifting aliens using guns, GLOO cannons, and stolen alien powers, with every door and vent offering alternate approaches.",
    color: "#2c3e50",
  },
  {
    title: "Dishonored",
    developer: "Arkane Studios",
    year: 2012,
    genre: "Stealth / Immersive Sim",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One",
    length: "12–15 hours",
    coreLoop: "Combine supernatural powers like teleportation and time-stop with stealth and swordplay to assassinate or spare targets across open-ended levels in a plague-ridden city.",
    color: "#d4a017",
  },
  {
    title: "Deathloop",
    developer: "Arkane Studios",
    year: 2021,
    genre: "FPS / Immersive Sim",
    platforms: "PC, PS5, Xbox Series",
    length: "15–20 hours",
    coreLoop: "Eliminate eight targets across four districts in four time periods within a single looping day, learning routines and finding the sequence that lets you kill all eight in one loop.",
    color: "#e67e22",
  },
  {
    title: "It Takes Two",
    developer: "Hazelight Studios",
    year: 2021,
    genre: "Co-op / Platformer",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "10–14 hours",
    coreLoop: "Play split-screen co-op as a divorcing couple turned into dolls, with each level introducing completely new mechanics — magnets, time clones, size-shifting — that require constant coordination.",
    color: "#e74c3c",
  },
  {
    title: "Titanfall 2",
    developer: "Respawn Entertainment",
    year: 2016,
    genre: "FPS",
    platforms: "PC, PS4, Xbox One",
    length: "6–8 hours",
    coreLoop: "Wall-run and double-jump through fast FPS combat as a pilot, then call in and fight inside a giant mech with its own weapon systems and traversal abilities.",
    color: "#34495e",
  },
  {
    title: "Monster Hunter: World",
    developer: "Capcom",
    year: 2018,
    genre: "Action RPG",
    platforms: "PC, PS4, Xbox One",
    length: "50–100+ hours",
    coreLoop: "Track and fight massive creatures across living ecosystems using one of fourteen weapon types, then carve materials to craft better armor and weapons to hunt bigger targets.",
    color: "#d4a017",
  },
  {
    title: "Hollow Knight: Silksong",
    developer: "Team Cherry",
    year: 2025,
    genre: "Metroidvania",
    platforms: "PC, Switch",
    length: "20–35 hours",
    coreLoop: "Explore an ascending kingdom as a nimble hornet warrior, using thread-based combat and acrobatic movement abilities to fight through interconnected regions and challenging bosses.",
    color: "#c0392b",
  },
  {
    title: "Returnal",
    developer: "Housemarque",
    year: 2021,
    genre: "Roguelike / Third-Person Shooter",
    platforms: "PS5, PC",
    length: "15–25 hours",
    coreLoop: "Die and restart on an ever-shifting alien planet, dash-dodging through bullet-hell patterns in third-person while collecting randomized weapon traits and parasites that trade buffs for debuffs.",
    color: "#1a3a2e",
  },
  {
    title: "Star Fox 64",
    developer: "Nintendo",
    year: 1997,
    genre: "Rail Shooter",
    platforms: "N64, 3DS",
    length: "1–2 hours per playthrough",
    coreLoop: "Fly through on-rails corridors and open arenas in an Arwing starfighter, barrel-rolling to deflect lasers and chasing high scores across branching mission paths.",
    color: "#2ecc71",
  },
  {
    title: "Tetris Effect: Connected",
    developer: "Enhance",
    year: 2018,
    genre: "Puzzle",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "2–4 hours for Journey mode, endless replayability",
    coreLoop: "Clear lines in Tetris as music, particles, and visuals pulse in sync with your inputs, with a Zone mechanic that freezes time to set up massive multi-line clears.",
    color: "#6c3483",
  },
  {
    title: "Super Smash Bros. Ultimate",
    developer: "Bandai Namco / Nintendo",
    year: 2018,
    genre: "Fighting / Platform Fighter",
    platforms: "Switch",
    length: "Open-ended, 20+ hours for World of Light",
    coreLoop: "Launch opponents off-stage using a unique moveset per character in a platform fighter where damage accumulates as knockback percentage rather than depleting a health bar.",
    color: "#e74c3c",
  },
  {
    title: "Mario Kart 8 Deluxe",
    developer: "Nintendo",
    year: 2017,
    genre: "Racing",
    platforms: "Switch",
    length: "Open-ended",
    coreLoop: "Race across inventive anti-gravity tracks, collecting item boxes to attack rivals or defend yourself, drifting for turbo boosts and managing position-dependent item luck.",
    color: "#e74c3c",
  },
  {
    title: "Dark Souls II",
    developer: "FromSoftware",
    year: 2014,
    genre: "Action RPG / Souls-like",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One",
    length: "35–50 hours",
    coreLoop: "Explore a sprawling kingdom of fog-gated bosses using stamina-based combat with an adaptability stat governing dodge effectiveness, collecting souls and human effigies to maintain max HP.",
    color: "#4a3728",
  },
  {
    title: "Armored Core VI: Fires of Rubicon",
    developer: "FromSoftware",
    year: 2023,
    genre: "Mech Action",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "15–25 hours",
    coreLoop: "Build custom mechs from hundreds of parts and fight through mission-based mech combat with aggressive movement, stagger mechanics, and build-specific strategies against massive bosses.",
    color: "#5d6d7e",
  },
  {
    title: "Bioshock Infinite",
    developer: "Irrational Games",
    year: 2013,
    genre: "FPS",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One, Switch",
    length: "12–15 hours",
    coreLoop: "Fight through a floating city using guns and vigors — magical hand powers — while riding skylines to reposition, and direct an AI companion to toss you ammo, health, and tears in reality.",
    color: "#3498db",
  },
  {
    title: "Bayonetta",
    developer: "PlatinumGames",
    year: 2009,
    genre: "Action / Character Action",
    platforms: "PS3, Xbox 360, Wii U, Switch, PC",
    length: "8–10 hours",
    coreLoop: "Chain combos of punches, kicks, and gunfire to trigger Witch Time on perfect dodges, building magic to summon massive demonic finishers against angelic enemies.",
    color: "#8e44ad",
  },
  {
    title: "Devil May Cry 5",
    developer: "Capcom",
    year: 2019,
    genre: "Action / Character Action",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "10–12 hours",
    coreLoop: "Style-switch between three playable characters with wildly different combat systems — sword combos, mechanical arms, and shape-shifting weapons — chasing SSS style rankings.",
    color: "#922b21",
  },
  {
    title: "NieR: Automata",
    developer: "PlatinumGames",
    year: 2017,
    genre: "Action RPG",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "20–40 hours across all routes",
    coreLoop: "Slash through machines in hack-and-slash combat that seamlessly shifts between 3D action, side-scrolling, and twin-stick shooter perspectives, replaying the story from new angles to reach the true ending.",
    color: "#5d6d7e",
  },
  {
    title: "Xenoblade Chronicles 3",
    developer: "Monolith Soft",
    year: 2022,
    genre: "JRPG",
    platforms: "Switch",
    length: "60–100+ hours",
    coreLoop: "Explore vast landscapes with a party of six using auto-attacking real-time combat where you position and swap between arts, chain attacks, and class interlinks to build massive damage combos.",
    color: "#1a5276",
  },
  {
    title: "The Legend of Zelda: A Link to the Past",
    developer: "Nintendo",
    year: 1991,
    genre: "Action / Adventure",
    platforms: "SNES, GBA, Switch (NSO)",
    length: "10–15 hours",
    coreLoop: "Explore a light and dark world in top-down action, navigating dungeons to collect items that serve as both weapons and keys to new areas.",
    color: "#27ae60",
  },
  {
    title: "The Legend of Zelda: Ocarina of Time",
    developer: "Nintendo",
    year: 1998,
    genre: "Action / Adventure",
    platforms: "N64, 3DS, Switch (NSO)",
    length: "15–25 hours",
    coreLoop: "Travel between child and adult timelines using a magical instrument, exploring dungeons with lock-and-key items, Z-targeting enemies in 3D combat, and riding across a central overworld.",
    color: "#27ae60",
  },
  {
    title: "The Legend of Zelda: Majora's Mask",
    developer: "Nintendo",
    year: 2000,
    genre: "Action / Adventure",
    platforms: "N64, 3DS, Switch (NSO)",
    length: "15–25 hours",
    coreLoop: "Relive the same three days before a moon crashes, using transformation masks to inhabit different bodies and helping NPCs on fixed schedules across a dense, interconnected town.",
    color: "#6c3483",
  },
  {
    title: "Castlevania: Symphony of the Night",
    developer: "Konami",
    year: 1997,
    genre: "Metroidvania",
    platforms: "PS1, PS4, Xbox 360, Mobile",
    length: "8–12 hours",
    coreLoop: "Explore a sprawling gothic castle as a dhampir, leveling up with RPG stats and finding equipment and movement abilities that reveal hidden passages and an entire inverted second castle.",
    color: "#4a0e4e",
  },
  {
    title: "Final Fantasy VI",
    developer: "Square",
    year: 1994,
    genre: "RPG",
    platforms: "SNES, GBA, PS1, PC, Mobile",
    length: "30–40 hours",
    coreLoop: "Command a large ensemble cast in ATB turn-based battles with character-specific abilities and equippable Espers, navigating a story that splits the world open halfway through.",
    color: "#2c3e50",
  },
  {
    title: "EarthBound",
    developer: "HAL Laboratory / Ape",
    year: 1994,
    genre: "RPG",
    platforms: "SNES, Switch (NSO)",
    length: "25–35 hours",
    coreLoop: "Fight quirky enemies in a modern-day setting using rolling HP meters and PSI powers in first-person turn-based combat, exploring suburbs, deserts, and your own subconscious.",
    color: "#e74c3c",
  },
  {
    title: "Mega Man 2",
    developer: "Capcom",
    year: 1988,
    genre: "Platformer",
    platforms: "NES, Switch (collections), PC",
    length: "2–4 hours",
    coreLoop: "Choose which robot master stage to tackle in any order, defeating each boss to steal their weapon and exploiting weakness chains to clear the remaining stages.",
    color: "#2980b9",
  },
  {
    title: "Sonic the Hedgehog 2",
    developer: "Sega",
    year: 1992,
    genre: "Platformer",
    platforms: "Genesis, Switch, PC, Mobile",
    length: "2–3 hours",
    coreLoop: "Build momentum through loops and ramps at high speed, collecting rings as both currency and a one-hit shield, spin-dashing through enemies across themed zones.",
    color: "#2980b9",
  },
  {
    title: "Pac-Man",
    developer: "Namco",
    year: 1980,
    genre: "Arcade",
    platforms: "Arcade, everything",
    length: "Minutes per game",
    coreLoop: "Navigate a maze eating dots while avoiding four ghosts with distinct behavior patterns, grabbing power pellets to temporarily turn the tables and eat them instead.",
    color: "#f1c40f",
  },
  {
    title: "Tetris",
    developer: "Alexey Pajitnov",
    year: 1984,
    genre: "Puzzle",
    platforms: "Everything",
    length: "Minutes per game",
    coreLoop: "Rotate and place falling tetrominoes to complete horizontal lines, managing an increasingly fast drop speed until the stack reaches the top.",
    color: "#3498db",
  },
  {
    title: "Wii Sports",
    developer: "Nintendo",
    year: 2006,
    genre: "Sports / Party",
    platforms: "Wii",
    length: "Open-ended",
    coreLoop: "Swing, throw, and bowl using motion controls in simplified sports simulations — tennis, bowling, boxing, baseball, golf — competing for skill ratings.",
    color: "#2ecc71",
  },
  {
    title: "Animal Crossing: New Horizons",
    developer: "Nintendo",
    year: 2020,
    genre: "Life Sim",
    platforms: "Switch",
    length: "50+ hours for main milestones",
    coreLoop: "Build and decorate an island home in real time, catching bugs and fish, crafting furniture, inviting villagers, and paying off house loans to Tom Nook in bells.",
    color: "#7dc95e",
  },
  {
    title: "Pokémon Red and Blue",
    developer: "Game Freak",
    year: 1996,
    genre: "RPG",
    platforms: "Game Boy",
    length: "25–35 hours",
    coreLoop: "Catch, train, and evolve 151 monsters using type-advantage turn-based battles, collecting gym badges across a region to challenge the Elite Four.",
    color: "#e74c3c",
  },
  {
    title: "Pokémon Legends: Arceus",
    developer: "Game Freak",
    year: 2022,
    genre: "Action RPG",
    platforms: "Switch",
    length: "25–35 hours",
    coreLoop: "Explore open areas in feudal Sinnoh, throwing Poké Balls in real-time to catch creatures in the wild, dodging their attacks, and filling out research tasks in a Pokédex.",
    color: "#2980b9",
  },
  {
    title: "Super Mario Bros.",
    developer: "Nintendo",
    year: 1985,
    genre: "Platformer",
    platforms: "NES, Switch (NSO)",
    length: "1–2 hours",
    coreLoop: "Run right through side-scrolling levels, jumping on enemies and hitting question blocks for power-ups, navigating pits and hazards to rescue the princess at the end of each world.",
    color: "#e74c3c",
  },
  {
    title: "Super Mario World",
    developer: "Nintendo",
    year: 1990,
    genre: "Platformer",
    platforms: "SNES, GBA, Switch (NSO)",
    length: "4–6 hours, 10+ for full completion",
    coreLoop: "Navigate a branching world map of secret exits, riding a dinosaur companion who eats enemies with different effects by shell color, across levels with hidden keyholes and star roads.",
    color: "#27ae60",
  },
  {
    title: "Super Mario 64",
    developer: "Nintendo",
    year: 1996,
    genre: "3D Platformer",
    platforms: "N64, Switch",
    length: "8–12 hours",
    coreLoop: "Jump into paintings to enter open sandbox levels, triple-jumping and wall-kicking through 3D space to collect stars from various objectives within each course.",
    color: "#e74c3c",
  },
  {
    title: "Half-Life",
    developer: "Valve",
    year: 1998,
    genre: "FPS",
    platforms: "PC",
    length: "10–12 hours",
    coreLoop: "Fight through a research facility gone wrong using an arsenal of weapons and environmental hazards, with story delivered entirely through in-world events rather than cutscenes.",
    color: "#d35400",
  },
  {
    title: "Half-Life: Alyx",
    developer: "Valve",
    year: 2020,
    genre: "FPS / VR",
    platforms: "PC (VR)",
    length: "10–12 hours",
    coreLoop: "Physically reach, grab, and reload weapons in VR while fighting headcrabs and Combine soldiers, solving puzzles with your actual hands in a terrifyingly immersive alien-occupied city.",
    color: "#d35400",
  },
  {
    title: "Amnesia: The Dark Descent",
    developer: "Frictional Games",
    year: 2010,
    genre: "Survival Horror",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "6–8 hours",
    coreLoop: "Explore a dark castle with no weapons, managing sanity that degrades in darkness and at the sight of monsters, hiding and running while solving physics-based puzzles.",
    color: "#1a1a1a",
  },
  {
    title: "Phasmophobia",
    developer: "Kinetic Games",
    year: 2020,
    genre: "Horror / Co-op",
    platforms: "PC, PS5, Xbox Series",
    length: "20–40 minutes per investigation",
    coreLoop: "Investigate haunted locations with ghost-hunting equipment — EMF readers, spirit boxes, UV lights — gathering evidence to identify the ghost type before it hunts you down.",
    color: "#2c3e50",
  },
  {
    title: "Valheim",
    developer: "Iron Gate Studio",
    year: 2021,
    genre: "Survival / Crafting",
    platforms: "PC, Xbox One, Xbox Series",
    length: "50–100+ hours",
    coreLoop: "Survive a procedural Norse purgatory by gathering resources, building Viking longhouses, sailing between biomes, and summoning mythological bosses to prove your worth.",
    color: "#2e4057",
  },
  {
    title: "Civilization VI",
    developer: "Firaxis Games",
    year: 2016,
    genre: "4X Strategy",
    platforms: "PC, PS4, Xbox One, Switch, Mobile",
    length: "10–20 hours per game",
    coreLoop: "Found cities, research technologies, and build wonders turn by turn across millennia, pursuing cultural, scientific, military, or religious victory against rival civilizations.",
    color: "#d4a017",
  },
  {
    title: "XCOM 2",
    developer: "Firaxis Games",
    year: 2016,
    genre: "Tactics / Strategy",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "30–50 hours",
    coreLoop: "Lead a squad of soldiers through turn-based tactical missions with permanent death, managing a resistance HQ between sorties by researching alien tech and recruiting new operatives.",
    color: "#2980b9",
  },
  {
    title: "Hades II",
    developer: "Supergiant Games",
    year: 2024,
    genre: "Roguelike / Action",
    platforms: "PC (Early Access)",
    length: "30–50 hours",
    coreLoop: "Fight through mythological realms using weapons and divine blessings in fast isometric combat, gathering resources between runs to unlock new paths, tools, and story progression.",
    color: "#6c3483",
  },
  {
    title: "1000xRESIST",
    developer: "sunset visitor",
    year: 2024,
    genre: "Adventure / Sci-Fi",
    platforms: "PC, Switch",
    length: "8–12 hours",
    coreLoop: "Relive memories as a clone investigating the history of humanity's last survivors, walking through narrative vignettes that shift genre and perspective to piece together a fractured truth.",
    color: "#e74c8b",
  },
  {
    title: "Astro Bot",
    developer: "Team Asobi",
    year: 2024,
    genre: "3D Platformer",
    platforms: "PS5",
    length: "8–12 hours",
    coreLoop: "Run, jump, and hover through inventive 3D levels as a tiny robot, using DualSense haptic feedback-driven power-ups and rescuing hidden bot friends scattered across themed worlds.",
    color: "#3498db",
  },
  {
    title: "Metaphor: ReFantazio",
    developer: "Studio Zero / Atlus",
    year: 2024,
    genre: "JRPG",
    platforms: "PC, PS4, PS5, Xbox Series",
    length: "80–100 hours",
    coreLoop: "Manage time between royal tournament deadlines, building social bonds and class-changing your party through a fast-forward turn-based and action-hybrid combat system in a fantasy kingdom.",
    color: "#1a3a5c",
  },

  // ============================================================
  // MAINSTREAM MULTIPLAYER / LIVE SERVICE
  // ============================================================
  {
    title: "Fortnite",
    developer: "Epic Games",
    year: 2017,
    genre: "Battle Royale / Shooter",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch, Mobile",
    length: "Open-ended, 20–25 minutes per match",
    coreLoop: "Drop onto an island with 99 others, loot weapons and materials, build walls and ramps for cover and positioning, and fight to be the last player standing as the storm closes in.",
    color: "#5b2fa0",
  },
  {
    title: "League of Legends",
    developer: "Riot Games",
    year: 2009,
    genre: "MOBA",
    platforms: "PC",
    length: "Open-ended, 25–45 minutes per match",
    coreLoop: "Pick a champion, lane against opponents, farm minions for gold, buy items between fights, and coordinate with four teammates to destroy the enemy nexus.",
    color: "#0a3d62",
  },
  {
    title: "Valorant",
    developer: "Riot Games",
    year: 2020,
    genre: "Tactical FPS",
    platforms: "PC, PS5, Xbox Series",
    length: "Open-ended, 30–40 minutes per match",
    coreLoop: "Play attack or defense in a 5v5 tactical shooter where each agent has unique abilities, buying weapons each round and aiming for headshots in one-life-per-round elimination.",
    color: "#fd4556",
  },
  {
    title: "Counter-Strike 2",
    developer: "Valve",
    year: 2023,
    genre: "Tactical FPS",
    platforms: "PC",
    length: "Open-ended, 30–45 minutes per match",
    coreLoop: "Buy weapons with round earnings, plant or defuse a bomb in 5v5 one-life rounds, mastering recoil patterns and map control with no respawns until the next round.",
    color: "#de9b35",
  },
  {
    title: "Counter-Strike: Global Offensive",
    developer: "Valve",
    year: 2012,
    genre: "Tactical FPS",
    platforms: "PC, PS3, Xbox 360",
    length: "Open-ended, 30–45 minutes per match",
    coreLoop: "Buy weapons at the start of each round, coordinate with your team to plant or defuse a bomb, and eliminate the opposing side in round-based tactical gunplay.",
    color: "#4a6741",
  },
  {
    title: "Overwatch 2",
    developer: "Blizzard Entertainment",
    year: 2022,
    genre: "Hero Shooter",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "Open-ended, 10–20 minutes per match",
    coreLoop: "Pick a hero with a unique kit of abilities in a 5v5 team shooter, switching heroes mid-match to counter the enemy composition across objective-based modes.",
    color: "#f99e1a",
  },
  {
    title: "Apex Legends",
    developer: "Respawn Entertainment",
    year: 2019,
    genre: "Battle Royale / Hero Shooter",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "Open-ended, 15–20 minutes per match",
    coreLoop: "Drop as a three-person squad, loot tiered gear, use legend-specific abilities for movement and combat advantage, and fight other squads as the ring closes.",
    color: "#cd3333",
  },
  {
    title: "Rocket League",
    developer: "Psyonix",
    year: 2015,
    genre: "Sports / Racing",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "Open-ended, 5–7 minutes per match",
    coreLoop: "Drive rocket-powered cars to hit a giant ball into the opponent's goal, boosting, jumping, and flying off walls in fast-paced aerial soccer.",
    color: "#005ba1",
  },
  {
    title: "Among Us",
    developer: "InnerSloth",
    year: 2018,
    genre: "Social Deduction",
    platforms: "PC, PS4, PS5, Xbox, Switch, Mobile",
    length: "Open-ended, 10–15 minutes per round",
    coreLoop: "Complete tasks around a map as a crewmate — or secretly murder and sabotage as an impostor — then debate and vote to eject the suspect during emergency meetings.",
    color: "#c51111",
  },
  {
    title: "Fall Guys",
    developer: "Mediatonic",
    year: 2020,
    genre: "Battle Royale / Party",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "Open-ended, 10–15 minutes per show",
    coreLoop: "Compete as a jellybean through rounds of obstacle courses, team games, and survival challenges, with players eliminated each round until one wins the crown.",
    color: "#ff69b4",
  },
  {
    title: "Destiny 2",
    developer: "Bungie",
    year: 2017,
    genre: "Looter Shooter / MMO",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "100+ hours",
    coreLoop: "Shoot aliens across planets and raids as one of three classes, chasing loot drops with randomized perks to build powerful loadouts for endgame PvE and PvP activities.",
    color: "#1a3a5c",
  },
  {
    title: "World of Warcraft",
    developer: "Blizzard Entertainment",
    year: 2004,
    genre: "MMORPG",
    platforms: "PC",
    length: "Open-ended, hundreds of hours",
    coreLoop: "Quest, dungeon-crawl, and raid with millions of other players in a persistent fantasy world, leveling a character, gearing up through endgame content, and coordinating in large-group encounters.",
    color: "#2e86c1",
  },
  {
    title: "Dota 2",
    developer: "Valve",
    year: 2013,
    genre: "MOBA",
    platforms: "PC",
    length: "Open-ended, 35–60 minutes per match",
    coreLoop: "Draft a hero from 120+ options, farm creeps in lanes for gold and XP, buy items that transform your power curve, and coordinate five-player teamfights to destroy the enemy Ancient.",
    color: "#be0000",
  },
  {
    title: "Rainbow Six Siege",
    developer: "Ubisoft Montreal",
    year: 2015,
    genre: "Tactical FPS",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "Open-ended, 20–30 minutes per match",
    coreLoop: "Pick an operator with unique gadgets, reinforce or breach destructible walls, and play one-life rounds of close-quarters attack-vs-defense with intel and angles as your main weapons.",
    color: "#2c3e50",
  },
  {
    title: "Grand Theft Auto V",
    developer: "Rockstar Games",
    year: 2013,
    genre: "Action / Open World",
    platforms: "PC, PS3, PS4, PS5, Xbox 360, Xbox One, Xbox Series",
    length: "30–35 hours story, open-ended online",
    coreLoop: "Switch between three protagonists across a sprawling city, driving, shooting, and heisting through a crime story — or join GTA Online for cooperative missions, races, and freemode chaos.",
    color: "#2ecc71",
  },
  {
    title: "Call of Duty: Modern Warfare 2 (2022)",
    developer: "Infinity Ward",
    year: 2022,
    genre: "FPS",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "6–8 hours campaign, open-ended multiplayer",
    coreLoop: "Sprint, aim, and shoot in fast-paced 6v6 multiplayer across small maps, earning killstreaks and unlocking weapon attachments through a prestige leveling system.",
    color: "#5d6d7e",
  },
  {
    title: "Call of Duty 4: Modern Warfare",
    developer: "Infinity Ward",
    year: 2007,
    genre: "FPS",
    platforms: "PC, PS3, Xbox 360",
    length: "6–8 hours campaign, open-ended multiplayer",
    coreLoop: "Shoot through a modern military campaign in cinematic set pieces, then compete in addictive multiplayer with create-a-class loadouts, perks, and killstreak rewards.",
    color: "#4a4a4a",
  },
  {
    title: "FIFA 23",
    developer: "EA Sports",
    year: 2022,
    genre: "Sports / Soccer",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "Open-ended",
    coreLoop: "Control a full soccer team in simulated matches, passing, dribbling, and shooting with real-world players, building an Ultimate Team through packs and trading.",
    color: "#1a5276",
  },
  {
    title: "NBA 2K24",
    developer: "Visual Concepts",
    year: 2023,
    genre: "Sports / Basketball",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series, Switch",
    length: "Open-ended",
    coreLoop: "Play full basketball games with real NBA rosters, timing shot releases and running plays, while building a MyPlayer career or managing a franchise.",
    color: "#e67e22",
  },
  {
    title: "Madden NFL 24",
    developer: "EA Tiburon",
    year: 2023,
    genre: "Sports / Football",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "Open-ended",
    coreLoop: "Call offensive and defensive plays in simulated NFL games, managing rosters across franchise mode or building a competitive squad in Ultimate Team.",
    color: "#1e8449",
  },
  {
    title: "Minecraft Dungeons",
    developer: "Mojang / Double Eleven",
    year: 2020,
    genre: "Action RPG / Dungeon Crawler",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "8–12 hours",
    coreLoop: "Hack through procedural dungeons in an isometric Minecraft-themed crawler, equipping randomized gear and enchantments in co-op with up to four players.",
    color: "#5d8c3e",
  },
  {
    title: "Sea of Thieves",
    developer: "Rare",
    year: 2018,
    genre: "Action / Adventure / Pirate",
    platforms: "PC, Xbox One, Xbox Series, PS5",
    length: "Open-ended",
    coreLoop: "Crew a pirate ship with friends, sailing between islands to dig up treasure, fight skeletons, and engage other player ships in cannon battles while managing sails and bailing water.",
    color: "#1abc9c",
  },
  {
    title: "Left 4 Dead 2",
    developer: "Valve",
    year: 2009,
    genre: "Co-op FPS",
    platforms: "PC, Xbox 360",
    length: "8–10 hours campaign, open-ended versus",
    coreLoop: "Fight through zombie hordes as a four-player team using guns and melee weapons, with an AI Director that dynamically adjusts enemy spawns based on your performance.",
    color: "#c0392b",
  },
  {
    title: "Deep Rock Galactic",
    developer: "Ghost Ship Games",
    year: 2020,
    genre: "Co-op FPS",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "50+ hours, 20–30 minutes per mission",
    coreLoop: "Mine minerals in fully destructible procedural caves as space dwarves, fighting alien bugs in four-player co-op with class-based roles and terrain-altering tools.",
    color: "#d35400",
  },
  {
    title: "Lethal Company",
    developer: "Zeekerss",
    year: 2023,
    genre: "Co-op Horror",
    platforms: "PC",
    length: "Open-ended, 30–60 minutes per moon",
    coreLoop: "Land on procedurally generated moons as a scavenging crew, collecting scrap from haunted facilities to meet a profit quota while avoiding or fleeing from monsters.",
    color: "#1a1a1a",
  },
  {
    title: "Palworld",
    developer: "Pocketpair",
    year: 2024,
    genre: "Survival / Creature Collector",
    platforms: "PC, Xbox One, Xbox Series",
    length: "50+ hours",
    coreLoop: "Capture creatures and put them to work in your base — farming, mining, crafting, and fighting — in an open-world survival game that blends monster-catching with factory building.",
    color: "#3498db",
  },
  {
    title: "Helldivers 2",
    developer: "Arrowhead Game Studios",
    year: 2024,
    genre: "Co-op Shooter",
    platforms: "PC, PS5",
    length: "50+ hours, 15–40 minutes per mission",
    coreLoop: "Drop onto hostile planets in four-player co-op, calling in airstrikes and resupply pods via stratagems while fighting overwhelming alien and robot forces for managed democracy.",
    color: "#f1c40f",
  },
  {
    title: "Diablo IV",
    developer: "Blizzard Entertainment",
    year: 2023,
    genre: "Action RPG",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "30–40 hours campaign, hundreds for endgame",
    coreLoop: "Slay demons across a dark open world, cycling through ability cooldowns and chasing loot with randomized affixes to push increasingly difficult endgame dungeons and seasonal content.",
    color: "#6c3483",
  },
  {
    title: "Monster Hunter Rise",
    developer: "Capcom",
    year: 2021,
    genre: "Action RPG",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "30–60 hours, hundreds for endgame",
    coreLoop: "Hunt massive monsters with one of fourteen weapon types, using wirebugs for aerial mobility, then carve materials to forge better gear and take on tougher targets.",
    color: "#2c3e50",
  },
  {
    title: "Elden Ring: Shadow of the Erdtree",
    developer: "FromSoftware",
    year: 2024,
    genre: "Action RPG / DLC",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "30–50 hours",
    coreLoop: "Explore a massive new region of punishing boss fights and hidden paths, collecting map fragments and scadutree blessings to power up within the DLC's self-contained progression.",
    color: "#8b7355",
  },
  {
    title: "The Finals",
    developer: "Embark Studios",
    year: 2023,
    genre: "FPS / Game Show",
    platforms: "PC, PS5, Xbox Series",
    length: "Open-ended, 10–15 minutes per match",
    coreLoop: "Compete in a destructible-environment FPS game show, smashing through walls and floors with your team to steal and deposit a vault in a fully demolishable arena.",
    color: "#e74c3c",
  },
  {
    title: "Escape from Tarkov",
    developer: "Battlestate Games",
    year: 2017,
    genre: "Extraction Shooter / Survival",
    platforms: "PC",
    length: "Open-ended, 20–45 minutes per raid",
    coreLoop: "Enter raids with gear you can permanently lose, loot military zones and fight other players and AI, then extract before the timer runs out to keep everything you found.",
    color: "#2c3e50",
  },
  {
    title: "Hunt: Showdown",
    developer: "Crytek",
    year: 2019,
    genre: "Extraction Shooter / Horror",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "Open-ended, 20–40 minutes per match",
    coreLoop: "Track and kill PvE boss monsters in a Louisiana swamp using 19th-century weapons, then extract the bounty while other player teams hunt you for the same prize.",
    color: "#4a3728",
  },
  {
    title: "Splatoon 3",
    developer: "Nintendo",
    year: 2022,
    genre: "Third-Person Shooter",
    platforms: "Switch",
    length: "Open-ended, 3–5 minutes per match",
    coreLoop: "Ink the ground in your team's color using paint-based weapons in 4v4 turf wars, swimming through your own ink for speed and stealth while splatting opponents.",
    color: "#e74c8b",
  },
  {
    title: "Street Fighter 6",
    developer: "Capcom",
    year: 2023,
    genre: "Fighting",
    platforms: "PC, PS4, PS5, Xbox Series",
    length: "Open-ended, 2–5 minutes per match",
    coreLoop: "Duel opponents in 1v1 fighting game rounds using normal attacks, special moves, and a Drive System that meters offensive and defensive options like parries, reversals, and powered-up specials.",
    color: "#1a5276",
  },
  {
    title: "Tekken 8",
    developer: "Bandai Namco",
    year: 2024,
    genre: "Fighting",
    platforms: "PC, PS5, Xbox Series",
    length: "Open-ended, 2–5 minutes per match",
    coreLoop: "Fight in 3D one-on-one matches using character-specific martial arts movesets, juggling opponents with combo strings and managing an aggressive Heat system that rewards offense.",
    color: "#c0392b",
  },
  {
    title: "Guilty Gear Strive",
    developer: "Arc System Works",
    year: 2021,
    genre: "Fighting",
    platforms: "PC, PS4, PS5, Xbox Series",
    length: "Open-ended, 2–5 minutes per match",
    coreLoop: "Clash in anime-styled 1v1 fighting with Roman Cancels that let you freeze and extend combos, managing burst and tension meters in a heavy-metal-scored air-dasher.",
    color: "#e74c3c",
  },
  {
    title: "Mario Party Superstars",
    developer: "NDcube",
    year: 2021,
    genre: "Party",
    platforms: "Switch",
    length: "1–2 hours per game",
    coreLoop: "Roll dice to move across a board game, buy stars with coins, and compete in quick minigames after every round — sabotaging friends with items and stolen stars along the way.",
    color: "#e74c3c",
  },
  {
    title: "Overcooked! 2",
    developer: "Ghost Town Games",
    year: 2018,
    genre: "Co-op / Party",
    platforms: "PC, PS4, Xbox One, Switch",
    length: "6–10 hours",
    coreLoop: "Chop, cook, plate, and serve recipes in increasingly chaotic kitchens with up to four players, coordinating who does what as the kitchen literally falls apart beneath you.",
    color: "#e67e22",
  },
  {
    title: "Rust",
    developer: "Facepunch Studios",
    year: 2018,
    genre: "Survival / Multiplayer",
    platforms: "PC, PS4, Xbox One",
    length: "Open-ended",
    coreLoop: "Spawn naked on a beach, gather resources, build a base, craft weapons, and survive against both the environment and other players who will raid your home while you sleep.",
    color: "#922b21",
  },
  {
    title: "Ark: Survival Evolved",
    developer: "Studio Wildcard",
    year: 2017,
    genre: "Survival / MMO",
    platforms: "PC, PS4, Xbox One, Switch, Mobile",
    length: "Open-ended, hundreds of hours",
    coreLoop: "Survive on an island of dinosaurs, taming and riding them by knocking them out and feeding them, while building bases, crafting gear, and fighting other tribes on multiplayer servers.",
    color: "#2e4057",
  },
];

// Exclude games that don't have generated screenshots available.
const EXCLUDED_TITLES_FOR_SCREENSHOTS = new Set<string>([
  "FEZ",
  "God of War (2018)",
  "Half-Life 2",
  "Resident Evil 4 (2023)",
  "Resident Evil 2 (2019)",
  "Demon's Souls (2020)",
  "Silent Hill 2 (2024)",
  "Dishonored",
  "Mario Kart 8 Deluxe",
  "Bayonetta",
  "Xenoblade Chronicles 3",
  "Sonic the Hedgehog 2",
  "Pokémon Red and Blue",
  "Half-Life",
  "Half-Life: Alyx",
  "Civilization VI",
  "Counter-Strike: Global Offensive",
  "Fall Guys",
  "World of Warcraft",
  "Call of Duty 4: Modern Warfare",
  "Rust",
]);

export const GAMES_DB: GameEntry[] = seededShuffle(
  RAW_GAMES_DB.filter((g) => !EXCLUDED_TITLES_FOR_SCREENSHOTS.has(g.title)),
  SHUFFLE_SEED
);

/** Sorted title list for autocomplete — deduplicated */
export const GAME_TITLES = GAMES_DB.map((g) => g.title)
  .filter((title, index, arr) => arr.indexOf(title) === index)
  .sort();
