import { GameEntry } from "./types";

/**
 * Static game database.
 *
 * CLUE ORDER: length → platforms → year → genre → developer → coreLoop
 *
 * WRITING GUIDELINES:
 * - length: First-playthrough estimate. Be specific ("6–8 hours") not vague ("medium").
 *   Include qualifiers when relevant ("40–60 hours for main story, 100+ for completion").
 * - coreLoop: One sentence describing what you DO, not what the game IS ABOUT.
 *   Good: "Dash, wall-climb, and air-dash through precision platforming rooms, dying and retrying in seconds."
 *   Bad: "A platformer about climbing a mountain." (that's a description, not a loop)
 *   The loop should be recognizable to someone who's played the game and
 *   unmistakable once combined with the other 5 clues.
 */
export const GAMES_DB: GameEntry[] = [
  {
    title: "Outer Wilds",
    developer: "Mobius Digital",
    year: 2019,
    genre: "Exploration / Mystery",
    platforms: "PC, PS4, Xbox, Switch",
    length: "15–20 hours",
    coreLoop: "Explore a solar system within a 22-minute time loop, piecing together an ancient mystery from environmental clues before the sun explodes.",
    color: "#1a3a5c",
  },
  {
    title: "Celeste",
    developer: "Maddy Thorson",
    year: 2018,
    genre: "Platformer",
    platforms: "PC, PS4, Xbox, Switch",
    length: "6–8 hours",
    coreLoop: "Dash, wall-climb, and air-dash through precision platforming rooms, dying and retrying in seconds with instant respawn.",
    color: "#6b2fa0",
  },
  {
    title: "Inside",
    developer: "Playdead",
    year: 2016,
    genre: "Puzzle Platformer",
    platforms: "PC, PS4, Xbox, Switch",
    length: "3–4 hours",
    coreLoop: "Move right through a wordless dystopia, solving physics-based environmental puzzles to avoid capture and death.",
    color: "#2c2c2c",
  },
  {
    title: "Kentucky Route Zero",
    developer: "Cardboard Computer",
    year: 2020,
    genre: "Adventure / Magical Realism",
    platforms: "PC, PS4, Xbox, Switch",
    length: "6–8 hours",
    coreLoop: "Navigate dialogue choices and point-and-click exploration through surreal, stage-like scenes along a secret highway beneath Kentucky.",
    color: "#1e3326",
  },
  {
    title: "Sekiro: Shadows Die Twice",
    developer: "FromSoftware",
    year: 2019,
    genre: "Action / Souls-like",
    platforms: "PC, PS4, Xbox",
    length: "30–40 hours",
    coreLoop: "Deflect enemy attacks with precise sword parries to break their posture, then deliver a killing deathblow, using a prosthetic arm for tactical tools.",
    color: "#8b1a1a",
  },
  {
    title: "Hollow Knight",
    developer: "Team Cherry",
    year: 2017,
    genre: "Metroidvania",
    platforms: "PC, PS4, Xbox, Switch",
    length: "25–40 hours",
    coreLoop: "Explore an interconnected underground kingdom, fighting bugs with a nail, unlocking movement abilities to reach new areas, and resting at benches to save.",
    color: "#1a1a2e",
  },
  {
    title: "Hades",
    developer: "Supergiant Games",
    year: 2020,
    genre: "Roguelike / Action",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "20–30 hours",
    coreLoop: "Fight through randomized rooms of enemies using a weapon and god-given boons, die, return to a hub with permanent upgrades, and advance the story with each run.",
    color: "#a0522d",
  },
  {
    title: "Disco Elysium",
    developer: "ZA/UM",
    year: 2019,
    genre: "RPG / Detective",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "25–35 hours",
    coreLoop: "Investigate a murder through dialogue trees and skill checks, where your own psyche's competing voices shape how you interpret every conversation.",
    color: "#4a6741",
  },
  {
    title: "Return of the Obra Dinn",
    developer: "Lucas Pope",
    year: 2018,
    genre: "Mystery / Logic Puzzle",
    platforms: "PC, PS4, Xbox, Switch",
    length: "8–12 hours",
    coreLoop: "Use a pocket watch to witness the moment of each crew member's death, then cross-reference visual and audio clues to identify who they were and what killed them.",
    color: "#e8e8d0",
  },
  {
    title: "Undertale",
    developer: "Toby Fox",
    year: 2015,
    genre: "RPG",
    platforms: "PC, PS4, Switch",
    length: "5–7 hours",
    coreLoop: "Navigate bullet-hell-style attack patterns in turn-based encounters, choosing to fight or spare every enemy through a mercy system that changes the story.",
    color: "#222034",
  },
  {
    title: "The Witness",
    developer: "Thekla, Inc.",
    year: 2016,
    genre: "Puzzle / Exploration",
    platforms: "PC, PS4, Xbox",
    length: "15–25 hours",
    coreLoop: "Solve increasingly complex line-drawing maze puzzles on panels scattered across an open island, learning each area's unique rule set through observation.",
    color: "#5c8a4d",
  },
  {
    title: "Braid",
    developer: "Jonathan Blow",
    year: 2008,
    genre: "Puzzle Platformer",
    platforms: "PC, PS3, Xbox 360",
    length: "4–6 hours",
    coreLoop: "Manipulate time — rewinding, slowing, and splitting it — to solve platforming puzzles and collect jigsaw pieces across thematic worlds.",
    color: "#c97b3d",
  },
  {
    title: "Dark Souls",
    developer: "FromSoftware",
    year: 2011,
    genre: "Action RPG / Souls-like",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One, Switch",
    length: "40–60 hours",
    coreLoop: "Fight through punishing enemies and bosses using stamina-based melee combat, recover souls from your corpse on death, and unlock shortcuts between bonfires.",
    color: "#3d2b1f",
  },
  {
    title: "Portal 2",
    developer: "Valve",
    year: 2011,
    genre: "Puzzle / FPS",
    platforms: "PC, PS3, Xbox 360",
    length: "7–9 hours",
    coreLoop: "Shoot linked entry and exit portals onto surfaces to redirect yourself, objects, and physics to traverse test chambers and escape a facility run by a murderous AI.",
    color: "#1e6091",
  },
  {
    title: "Shadow of the Colossus",
    developer: "Team Ico",
    year: 2005,
    genre: "Action / Adventure",
    platforms: "PS2, PS3, PS4",
    length: "6–8 hours",
    coreLoop: "Ride across an empty forbidden land to find towering colossi, then climb their bodies to locate and strike glowing weak points.",
    color: "#8a9a5b",
  },
  {
    title: "Limbo",
    developer: "Playdead",
    year: 2010,
    genre: "Puzzle Platformer",
    platforms: "PC, PS3, PS4, Xbox 360, Xbox One, Switch",
    length: "3–4 hours",
    coreLoop: "Move through a monochromatic, hostile world solving physics puzzles and avoiding traps, dying gruesomely and restarting from nearby checkpoints.",
    color: "#1a1a1a",
  },
  {
    title: "Stardew Valley",
    developer: "ConcernedApe",
    year: 2016,
    genre: "Simulation / RPG",
    platforms: "PC, PS4, Xbox, Switch, Mobile",
    length: "50–100+ hours",
    coreLoop: "Farm crops, raise animals, mine resources, fish, and build relationships with townsfolk across seasons, reinvesting profits to expand your homestead.",
    color: "#4a8c3f",
  },
  {
    title: "Spelunky 2",
    developer: "Mossmouth",
    year: 2020,
    genre: "Roguelike / Platformer",
    platforms: "PC, PS4, Switch",
    length: "50+ hours to first clear, minutes per run",
    coreLoop: "Navigate procedurally generated caves full of traps and enemies in short, high-stakes runs where a single mistake cascades into death and a full restart.",
    color: "#c4a35a",
  },
  {
    title: "Neon White",
    developer: "Angel Matrix",
    year: 2022,
    genre: "FPS / Speedrunning",
    platforms: "PC, PS4, PS5, Switch",
    length: "7–10 hours",
    coreLoop: "Blitz through short levels by shooting demons and discarding weapon cards to gain movement abilities like double jumps and dashes, chasing faster completion times.",
    color: "#e8e8e8",
  },
  {
    title: "Tunic",
    developer: "Andrew Shouldice",
    year: 2022,
    genre: "Action / Adventure",
    platforms: "PC, PS4, PS5, Xbox, Switch",
    length: "12–15 hours",
    coreLoop: "Explore an isometric world as a small fox, fighting enemies with a sword and shield while discovering and decoding pages of an in-game instruction manual written in a foreign script.",
    color: "#3fa67e",
  },
  {
    title: "Elden Ring",
    developer: "FromSoftware",
    year: 2022,
    genre: "Action RPG / Open World",
    platforms: "PC, PS4, PS5, Xbox One, Xbox Series",
    length: "60–100+ hours",
    coreLoop: "Explore a vast open world on horseback, discover dungeons and bosses organically, level up at sites of grace, and fight through punishing combat with build-crafted weapons and spells.",
    color: "#6b5b3e",
  },
  {
    title: "Bloodborne",
    developer: "FromSoftware",
    year: 2015,
    genre: "Action RPG / Souls-like",
    platforms: "PS4",
    length: "30–40 hours",
    coreLoop: "Hunt beasts through gothic streets using fast, aggressive trick-weapon combat with a rally system that rewards attacking immediately after taking damage.",
    color: "#2b0a0a",
  },
  {
    title: "Journey",
    developer: "thatgamecompany",
    year: 2012,
    genre: "Adventure",
    platforms: "PS3, PS4, PC",
    length: "1.5–2 hours",
    coreLoop: "Walk and fly through vast desert landscapes toward a distant mountain, occasionally encountering one anonymous companion with no communication except musical chimes.",
    color: "#d4a44c",
  },
  {
    title: "The Last of Us",
    developer: "Naughty Dog",
    year: 2013,
    genre: "Action / Adventure",
    platforms: "PS3, PS4, PS5, PC",
    length: "15–18 hours",
    coreLoop: "Scavenge scarce supplies, craft improvised weapons, and alternate between stealth and desperate combat against infected and hostile humans across a post-apocalyptic road story.",
    color: "#2d4a2e",
  },
  {
    title: "Breath of the Wild",
    developer: "Nintendo",
    year: 2017,
    genre: "Action / Adventure / Open World",
    platforms: "Switch, Wii U",
    length: "40–60 hours",
    coreLoop: "Climb, glide, and explore a fully open world, solving physics-based shrine puzzles, cooking food for buffs, and fighting enemies with breakable weapons in any order you choose.",
    color: "#5b9bd5",
  },
  {
    title: "Papers, Please",
    developer: "Lucas Pope",
    year: 2013,
    genre: "Simulation / Puzzle",
    platforms: "PC, Mobile",
    length: "4–6 hours",
    coreLoop: "Inspect travelers' documents at a border checkpoint against an ever-growing rulebook, stamping passports approved or denied while balancing income against moral choices.",
    color: "#5a5a3c",
  },
  {
    title: "Slay the Spire",
    developer: "MegaCrit",
    year: 2019,
    genre: "Roguelike / Deckbuilder",
    platforms: "PC, PS4, Xbox, Switch, Mobile",
    length: "50+ hours, 30–60 minutes per run",
    coreLoop: "Draft cards after each combat encounter to build a synergistic deck, manage HP across three acts of increasingly difficult fights, and start over on death with meta-progression.",
    color: "#6a1b3d",
  },
  {
    title: "What Remains of Edith Finch",
    developer: "Giant Sparrow",
    year: 2017,
    genre: "Adventure / Walking Sim",
    platforms: "PC, PS4, Xbox, Switch",
    length: "2–3 hours",
    coreLoop: "Walk through a labyrinthine family house, entering bedrooms to play through short vignettes that each use a unique mechanic to depict a family member's final moments.",
    color: "#4a3728",
  },
  {
    title: "Inscryption",
    developer: "Daniel Mullins",
    year: 2021,
    genre: "Deckbuilder / Horror",
    platforms: "PC, PS4, PS5, Switch",
    length: "10–12 hours",
    coreLoop: "Play cards with blood sacrifices against a shadowy opponent in a cabin, solving escape-room puzzles between rounds, as the game dismantles and rebuilds its own rules across acts.",
    color: "#0d0d0d",
  },
  {
    title: "Katamari Damacy",
    developer: "Namco",
    year: 2004,
    genre: "Puzzle / Action",
    platforms: "PS2, Switch, PC",
    length: "4–6 hours",
    coreLoop: "Roll an adhesive ball across environments, picking up increasingly larger objects to grow from thumbtacks to buildings within a time limit.",
    color: "#7dc95e",
  },
];

/** Sorted title list for autocomplete */
export const GAME_TITLES = GAMES_DB.map((g) => g.title).sort();
